// <auto-generated />
using System;
using Friendbook.DataAccess.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Friendbook.DataAccess.PostgreSql.Migrations
{
    [DbContext(typeof(FriendbookDbContext))]
    [Migration("20220116211601_FollowerPairs")]
    partial class FollowerPairs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Friendbook.DataAccess.PostgreSql.Entities.FollowerPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FollowerId")
                        .HasColumnType("integer");

                    b.Property<int>("FollowingId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRetroactive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("FollowerPairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FollowerId = 1,
                            FollowingId = 2,
                            IsRetroactive = false
                        });
                });

            modelBuilder.Entity("Friendbook.DataAccess.PostgreSql.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(2004, 1, 24),
                            FirstName = "Alexander",
                            LastName = "Konovalov",
                            Nickname = "shuryak"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(2003, 2, 16),
                            FirstName = "Ivan",
                            LastName = "Vdovin",
                            Nickname = "ivan03vdovin"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1998, 6, 10),
                            FirstName = "Artur",
                            LastName = "Ivanov",
                            Nickname = "archii"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
